language: java
sudo: required
os: linux

jdk:
- oraclejdk8

services:
  - docker
  
before_install:
- docker ps -a
- wget https://github.com/openshift/origin/releases/download/v3.6.0-rc.0/openshift-origin-client-tools-v3.6.0-rc.0-98b3d56-linux-64bit.tar.gz
- tar -xzvf openshift-origin-client-tools-v3.6.0-rc.0-98b3d56-linux-64bit.tar.gz
- ls -alh
- cd openshift-origin-client-tools-v3.6.0-rc.0-98b3d56-linux-64bit


script:
- ./oc cluster up
- ./oc cluster status
